
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ExperienceTag` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model ExperienceTag
 * 
 */
export type ExperienceTagModel = runtime.Types.Result.DefaultSelection<Prisma.$ExperienceTagPayload>

export type AggregateExperienceTag = {
  _count: ExperienceTagCountAggregateOutputType | null
  _avg: ExperienceTagAvgAggregateOutputType | null
  _sum: ExperienceTagSumAggregateOutputType | null
  _min: ExperienceTagMinAggregateOutputType | null
  _max: ExperienceTagMaxAggregateOutputType | null
}

export type ExperienceTagAvgAggregateOutputType = {
  experienceId: number | null
  tagId: number | null
}

export type ExperienceTagSumAggregateOutputType = {
  experienceId: number | null
  tagId: number | null
}

export type ExperienceTagMinAggregateOutputType = {
  experienceId: number | null
  tagId: number | null
}

export type ExperienceTagMaxAggregateOutputType = {
  experienceId: number | null
  tagId: number | null
}

export type ExperienceTagCountAggregateOutputType = {
  experienceId: number
  tagId: number
  _all: number
}


export type ExperienceTagAvgAggregateInputType = {
  experienceId?: true
  tagId?: true
}

export type ExperienceTagSumAggregateInputType = {
  experienceId?: true
  tagId?: true
}

export type ExperienceTagMinAggregateInputType = {
  experienceId?: true
  tagId?: true
}

export type ExperienceTagMaxAggregateInputType = {
  experienceId?: true
  tagId?: true
}

export type ExperienceTagCountAggregateInputType = {
  experienceId?: true
  tagId?: true
  _all?: true
}

export type ExperienceTagAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExperienceTag to aggregate.
   */
  where?: Prisma.ExperienceTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperienceTags to fetch.
   */
  orderBy?: Prisma.ExperienceTagOrderByWithRelationInput | Prisma.ExperienceTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExperienceTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperienceTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperienceTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ExperienceTags
  **/
  _count?: true | ExperienceTagCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExperienceTagAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExperienceTagSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExperienceTagMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExperienceTagMaxAggregateInputType
}

export type GetExperienceTagAggregateType<T extends ExperienceTagAggregateArgs> = {
      [P in keyof T & keyof AggregateExperienceTag]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExperienceTag[P]>
    : Prisma.GetScalarType<T[P], AggregateExperienceTag[P]>
}




export type ExperienceTagGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExperienceTagWhereInput
  orderBy?: Prisma.ExperienceTagOrderByWithAggregationInput | Prisma.ExperienceTagOrderByWithAggregationInput[]
  by: Prisma.ExperienceTagScalarFieldEnum[] | Prisma.ExperienceTagScalarFieldEnum
  having?: Prisma.ExperienceTagScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExperienceTagCountAggregateInputType | true
  _avg?: ExperienceTagAvgAggregateInputType
  _sum?: ExperienceTagSumAggregateInputType
  _min?: ExperienceTagMinAggregateInputType
  _max?: ExperienceTagMaxAggregateInputType
}

export type ExperienceTagGroupByOutputType = {
  experienceId: number
  tagId: number
  _count: ExperienceTagCountAggregateOutputType | null
  _avg: ExperienceTagAvgAggregateOutputType | null
  _sum: ExperienceTagSumAggregateOutputType | null
  _min: ExperienceTagMinAggregateOutputType | null
  _max: ExperienceTagMaxAggregateOutputType | null
}

type GetExperienceTagGroupByPayload<T extends ExperienceTagGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExperienceTagGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExperienceTagGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExperienceTagGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExperienceTagGroupByOutputType[P]>
      }
    >
  >



export type ExperienceTagWhereInput = {
  AND?: Prisma.ExperienceTagWhereInput | Prisma.ExperienceTagWhereInput[]
  OR?: Prisma.ExperienceTagWhereInput[]
  NOT?: Prisma.ExperienceTagWhereInput | Prisma.ExperienceTagWhereInput[]
  experienceId?: Prisma.IntFilter<"ExperienceTag"> | number
  tagId?: Prisma.IntFilter<"ExperienceTag"> | number
  experience?: Prisma.XOR<Prisma.ExperienceScalarRelationFilter, Prisma.ExperienceWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}

export type ExperienceTagOrderByWithRelationInput = {
  experienceId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  experience?: Prisma.ExperienceOrderByWithRelationInput
  tag?: Prisma.TagOrderByWithRelationInput
}

export type ExperienceTagWhereUniqueInput = Prisma.AtLeast<{
  experienceId_tagId?: Prisma.ExperienceTagExperienceIdTagIdCompoundUniqueInput
  AND?: Prisma.ExperienceTagWhereInput | Prisma.ExperienceTagWhereInput[]
  OR?: Prisma.ExperienceTagWhereInput[]
  NOT?: Prisma.ExperienceTagWhereInput | Prisma.ExperienceTagWhereInput[]
  experienceId?: Prisma.IntFilter<"ExperienceTag"> | number
  tagId?: Prisma.IntFilter<"ExperienceTag"> | number
  experience?: Prisma.XOR<Prisma.ExperienceScalarRelationFilter, Prisma.ExperienceWhereInput>
  tag?: Prisma.XOR<Prisma.TagScalarRelationFilter, Prisma.TagWhereInput>
}, "experienceId_tagId">

export type ExperienceTagOrderByWithAggregationInput = {
  experienceId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
  _count?: Prisma.ExperienceTagCountOrderByAggregateInput
  _avg?: Prisma.ExperienceTagAvgOrderByAggregateInput
  _max?: Prisma.ExperienceTagMaxOrderByAggregateInput
  _min?: Prisma.ExperienceTagMinOrderByAggregateInput
  _sum?: Prisma.ExperienceTagSumOrderByAggregateInput
}

export type ExperienceTagScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExperienceTagScalarWhereWithAggregatesInput | Prisma.ExperienceTagScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExperienceTagScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExperienceTagScalarWhereWithAggregatesInput | Prisma.ExperienceTagScalarWhereWithAggregatesInput[]
  experienceId?: Prisma.IntWithAggregatesFilter<"ExperienceTag"> | number
  tagId?: Prisma.IntWithAggregatesFilter<"ExperienceTag"> | number
}

export type ExperienceTagCreateInput = {
  experience: Prisma.ExperienceCreateNestedOneWithoutExperienceTagsInput
  tag: Prisma.TagCreateNestedOneWithoutExperienceTagsInput
}

export type ExperienceTagUncheckedCreateInput = {
  experienceId: number
  tagId: number
}

export type ExperienceTagUpdateInput = {
  experience?: Prisma.ExperienceUpdateOneRequiredWithoutExperienceTagsNestedInput
  tag?: Prisma.TagUpdateOneRequiredWithoutExperienceTagsNestedInput
}

export type ExperienceTagUncheckedUpdateInput = {
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExperienceTagCreateManyInput = {
  experienceId: number
  tagId: number
}

export type ExperienceTagUpdateManyMutationInput = {

}

export type ExperienceTagUncheckedUpdateManyInput = {
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExperienceTagListRelationFilter = {
  every?: Prisma.ExperienceTagWhereInput
  some?: Prisma.ExperienceTagWhereInput
  none?: Prisma.ExperienceTagWhereInput
}

export type ExperienceTagOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExperienceTagExperienceIdTagIdCompoundUniqueInput = {
  experienceId: number
  tagId: number
}

export type ExperienceTagCountOrderByAggregateInput = {
  experienceId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type ExperienceTagAvgOrderByAggregateInput = {
  experienceId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type ExperienceTagMaxOrderByAggregateInput = {
  experienceId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type ExperienceTagMinOrderByAggregateInput = {
  experienceId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type ExperienceTagSumOrderByAggregateInput = {
  experienceId?: Prisma.SortOrder
  tagId?: Prisma.SortOrder
}

export type ExperienceTagCreateNestedManyWithoutExperienceInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutExperienceInput, Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput> | Prisma.ExperienceTagCreateWithoutExperienceInput[] | Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput | Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput[]
  createMany?: Prisma.ExperienceTagCreateManyExperienceInputEnvelope
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
}

export type ExperienceTagUncheckedCreateNestedManyWithoutExperienceInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutExperienceInput, Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput> | Prisma.ExperienceTagCreateWithoutExperienceInput[] | Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput | Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput[]
  createMany?: Prisma.ExperienceTagCreateManyExperienceInputEnvelope
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
}

export type ExperienceTagUpdateManyWithoutExperienceNestedInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutExperienceInput, Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput> | Prisma.ExperienceTagCreateWithoutExperienceInput[] | Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput | Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput[]
  upsert?: Prisma.ExperienceTagUpsertWithWhereUniqueWithoutExperienceInput | Prisma.ExperienceTagUpsertWithWhereUniqueWithoutExperienceInput[]
  createMany?: Prisma.ExperienceTagCreateManyExperienceInputEnvelope
  set?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  disconnect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  delete?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  update?: Prisma.ExperienceTagUpdateWithWhereUniqueWithoutExperienceInput | Prisma.ExperienceTagUpdateWithWhereUniqueWithoutExperienceInput[]
  updateMany?: Prisma.ExperienceTagUpdateManyWithWhereWithoutExperienceInput | Prisma.ExperienceTagUpdateManyWithWhereWithoutExperienceInput[]
  deleteMany?: Prisma.ExperienceTagScalarWhereInput | Prisma.ExperienceTagScalarWhereInput[]
}

export type ExperienceTagUncheckedUpdateManyWithoutExperienceNestedInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutExperienceInput, Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput> | Prisma.ExperienceTagCreateWithoutExperienceInput[] | Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput | Prisma.ExperienceTagCreateOrConnectWithoutExperienceInput[]
  upsert?: Prisma.ExperienceTagUpsertWithWhereUniqueWithoutExperienceInput | Prisma.ExperienceTagUpsertWithWhereUniqueWithoutExperienceInput[]
  createMany?: Prisma.ExperienceTagCreateManyExperienceInputEnvelope
  set?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  disconnect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  delete?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  update?: Prisma.ExperienceTagUpdateWithWhereUniqueWithoutExperienceInput | Prisma.ExperienceTagUpdateWithWhereUniqueWithoutExperienceInput[]
  updateMany?: Prisma.ExperienceTagUpdateManyWithWhereWithoutExperienceInput | Prisma.ExperienceTagUpdateManyWithWhereWithoutExperienceInput[]
  deleteMany?: Prisma.ExperienceTagScalarWhereInput | Prisma.ExperienceTagScalarWhereInput[]
}

export type ExperienceTagCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutTagInput, Prisma.ExperienceTagUncheckedCreateWithoutTagInput> | Prisma.ExperienceTagCreateWithoutTagInput[] | Prisma.ExperienceTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutTagInput | Prisma.ExperienceTagCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.ExperienceTagCreateManyTagInputEnvelope
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
}

export type ExperienceTagUncheckedCreateNestedManyWithoutTagInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutTagInput, Prisma.ExperienceTagUncheckedCreateWithoutTagInput> | Prisma.ExperienceTagCreateWithoutTagInput[] | Prisma.ExperienceTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutTagInput | Prisma.ExperienceTagCreateOrConnectWithoutTagInput[]
  createMany?: Prisma.ExperienceTagCreateManyTagInputEnvelope
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
}

export type ExperienceTagUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutTagInput, Prisma.ExperienceTagUncheckedCreateWithoutTagInput> | Prisma.ExperienceTagCreateWithoutTagInput[] | Prisma.ExperienceTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutTagInput | Prisma.ExperienceTagCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.ExperienceTagUpsertWithWhereUniqueWithoutTagInput | Prisma.ExperienceTagUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.ExperienceTagCreateManyTagInputEnvelope
  set?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  disconnect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  delete?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  update?: Prisma.ExperienceTagUpdateWithWhereUniqueWithoutTagInput | Prisma.ExperienceTagUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.ExperienceTagUpdateManyWithWhereWithoutTagInput | Prisma.ExperienceTagUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.ExperienceTagScalarWhereInput | Prisma.ExperienceTagScalarWhereInput[]
}

export type ExperienceTagUncheckedUpdateManyWithoutTagNestedInput = {
  create?: Prisma.XOR<Prisma.ExperienceTagCreateWithoutTagInput, Prisma.ExperienceTagUncheckedCreateWithoutTagInput> | Prisma.ExperienceTagCreateWithoutTagInput[] | Prisma.ExperienceTagUncheckedCreateWithoutTagInput[]
  connectOrCreate?: Prisma.ExperienceTagCreateOrConnectWithoutTagInput | Prisma.ExperienceTagCreateOrConnectWithoutTagInput[]
  upsert?: Prisma.ExperienceTagUpsertWithWhereUniqueWithoutTagInput | Prisma.ExperienceTagUpsertWithWhereUniqueWithoutTagInput[]
  createMany?: Prisma.ExperienceTagCreateManyTagInputEnvelope
  set?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  disconnect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  delete?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  connect?: Prisma.ExperienceTagWhereUniqueInput | Prisma.ExperienceTagWhereUniqueInput[]
  update?: Prisma.ExperienceTagUpdateWithWhereUniqueWithoutTagInput | Prisma.ExperienceTagUpdateWithWhereUniqueWithoutTagInput[]
  updateMany?: Prisma.ExperienceTagUpdateManyWithWhereWithoutTagInput | Prisma.ExperienceTagUpdateManyWithWhereWithoutTagInput[]
  deleteMany?: Prisma.ExperienceTagScalarWhereInput | Prisma.ExperienceTagScalarWhereInput[]
}

export type ExperienceTagCreateWithoutExperienceInput = {
  tag: Prisma.TagCreateNestedOneWithoutExperienceTagsInput
}

export type ExperienceTagUncheckedCreateWithoutExperienceInput = {
  tagId: number
}

export type ExperienceTagCreateOrConnectWithoutExperienceInput = {
  where: Prisma.ExperienceTagWhereUniqueInput
  create: Prisma.XOR<Prisma.ExperienceTagCreateWithoutExperienceInput, Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput>
}

export type ExperienceTagCreateManyExperienceInputEnvelope = {
  data: Prisma.ExperienceTagCreateManyExperienceInput | Prisma.ExperienceTagCreateManyExperienceInput[]
  skipDuplicates?: boolean
}

export type ExperienceTagUpsertWithWhereUniqueWithoutExperienceInput = {
  where: Prisma.ExperienceTagWhereUniqueInput
  update: Prisma.XOR<Prisma.ExperienceTagUpdateWithoutExperienceInput, Prisma.ExperienceTagUncheckedUpdateWithoutExperienceInput>
  create: Prisma.XOR<Prisma.ExperienceTagCreateWithoutExperienceInput, Prisma.ExperienceTagUncheckedCreateWithoutExperienceInput>
}

export type ExperienceTagUpdateWithWhereUniqueWithoutExperienceInput = {
  where: Prisma.ExperienceTagWhereUniqueInput
  data: Prisma.XOR<Prisma.ExperienceTagUpdateWithoutExperienceInput, Prisma.ExperienceTagUncheckedUpdateWithoutExperienceInput>
}

export type ExperienceTagUpdateManyWithWhereWithoutExperienceInput = {
  where: Prisma.ExperienceTagScalarWhereInput
  data: Prisma.XOR<Prisma.ExperienceTagUpdateManyMutationInput, Prisma.ExperienceTagUncheckedUpdateManyWithoutExperienceInput>
}

export type ExperienceTagScalarWhereInput = {
  AND?: Prisma.ExperienceTagScalarWhereInput | Prisma.ExperienceTagScalarWhereInput[]
  OR?: Prisma.ExperienceTagScalarWhereInput[]
  NOT?: Prisma.ExperienceTagScalarWhereInput | Prisma.ExperienceTagScalarWhereInput[]
  experienceId?: Prisma.IntFilter<"ExperienceTag"> | number
  tagId?: Prisma.IntFilter<"ExperienceTag"> | number
}

export type ExperienceTagCreateWithoutTagInput = {
  experience: Prisma.ExperienceCreateNestedOneWithoutExperienceTagsInput
}

export type ExperienceTagUncheckedCreateWithoutTagInput = {
  experienceId: number
}

export type ExperienceTagCreateOrConnectWithoutTagInput = {
  where: Prisma.ExperienceTagWhereUniqueInput
  create: Prisma.XOR<Prisma.ExperienceTagCreateWithoutTagInput, Prisma.ExperienceTagUncheckedCreateWithoutTagInput>
}

export type ExperienceTagCreateManyTagInputEnvelope = {
  data: Prisma.ExperienceTagCreateManyTagInput | Prisma.ExperienceTagCreateManyTagInput[]
  skipDuplicates?: boolean
}

export type ExperienceTagUpsertWithWhereUniqueWithoutTagInput = {
  where: Prisma.ExperienceTagWhereUniqueInput
  update: Prisma.XOR<Prisma.ExperienceTagUpdateWithoutTagInput, Prisma.ExperienceTagUncheckedUpdateWithoutTagInput>
  create: Prisma.XOR<Prisma.ExperienceTagCreateWithoutTagInput, Prisma.ExperienceTagUncheckedCreateWithoutTagInput>
}

export type ExperienceTagUpdateWithWhereUniqueWithoutTagInput = {
  where: Prisma.ExperienceTagWhereUniqueInput
  data: Prisma.XOR<Prisma.ExperienceTagUpdateWithoutTagInput, Prisma.ExperienceTagUncheckedUpdateWithoutTagInput>
}

export type ExperienceTagUpdateManyWithWhereWithoutTagInput = {
  where: Prisma.ExperienceTagScalarWhereInput
  data: Prisma.XOR<Prisma.ExperienceTagUpdateManyMutationInput, Prisma.ExperienceTagUncheckedUpdateManyWithoutTagInput>
}

export type ExperienceTagCreateManyExperienceInput = {
  tagId: number
}

export type ExperienceTagUpdateWithoutExperienceInput = {
  tag?: Prisma.TagUpdateOneRequiredWithoutExperienceTagsNestedInput
}

export type ExperienceTagUncheckedUpdateWithoutExperienceInput = {
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExperienceTagUncheckedUpdateManyWithoutExperienceInput = {
  tagId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExperienceTagCreateManyTagInput = {
  experienceId: number
}

export type ExperienceTagUpdateWithoutTagInput = {
  experience?: Prisma.ExperienceUpdateOneRequiredWithoutExperienceTagsNestedInput
}

export type ExperienceTagUncheckedUpdateWithoutTagInput = {
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExperienceTagUncheckedUpdateManyWithoutTagInput = {
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
}



export type ExperienceTagSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  experienceId?: boolean
  tagId?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["experienceTag"]>

export type ExperienceTagSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  experienceId?: boolean
  tagId?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["experienceTag"]>

export type ExperienceTagSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  experienceId?: boolean
  tagId?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}, ExtArgs["result"]["experienceTag"]>

export type ExperienceTagSelectScalar = {
  experienceId?: boolean
  tagId?: boolean
}

export type ExperienceTagOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"experienceId" | "tagId", ExtArgs["result"]["experienceTag"]>
export type ExperienceTagInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}
export type ExperienceTagIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}
export type ExperienceTagIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  tag?: boolean | Prisma.TagDefaultArgs<ExtArgs>
}

export type $ExperienceTagPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ExperienceTag"
  objects: {
    experience: Prisma.$ExperiencePayload<ExtArgs>
    tag: Prisma.$TagPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    experienceId: number
    tagId: number
  }, ExtArgs["result"]["experienceTag"]>
  composites: {}
}

export type ExperienceTagGetPayload<S extends boolean | null | undefined | ExperienceTagDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload, S>

export type ExperienceTagCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExperienceTagFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExperienceTagCountAggregateInputType | true
  }

export interface ExperienceTagDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ExperienceTag'], meta: { name: 'ExperienceTag' } }
  /**
   * Find zero or one ExperienceTag that matches the filter.
   * @param {ExperienceTagFindUniqueArgs} args - Arguments to find a ExperienceTag
   * @example
   * // Get one ExperienceTag
   * const experienceTag = await prisma.experienceTag.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExperienceTagFindUniqueArgs>(args: Prisma.SelectSubset<T, ExperienceTagFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ExperienceTag that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExperienceTagFindUniqueOrThrowArgs} args - Arguments to find a ExperienceTag
   * @example
   * // Get one ExperienceTag
   * const experienceTag = await prisma.experienceTag.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExperienceTagFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExperienceTagFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExperienceTag that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperienceTagFindFirstArgs} args - Arguments to find a ExperienceTag
   * @example
   * // Get one ExperienceTag
   * const experienceTag = await prisma.experienceTag.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExperienceTagFindFirstArgs>(args?: Prisma.SelectSubset<T, ExperienceTagFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ExperienceTag that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperienceTagFindFirstOrThrowArgs} args - Arguments to find a ExperienceTag
   * @example
   * // Get one ExperienceTag
   * const experienceTag = await prisma.experienceTag.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExperienceTagFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExperienceTagFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ExperienceTags that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperienceTagFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ExperienceTags
   * const experienceTags = await prisma.experienceTag.findMany()
   * 
   * // Get first 10 ExperienceTags
   * const experienceTags = await prisma.experienceTag.findMany({ take: 10 })
   * 
   * // Only select the `experienceId`
   * const experienceTagWithExperienceIdOnly = await prisma.experienceTag.findMany({ select: { experienceId: true } })
   * 
   */
  findMany<T extends ExperienceTagFindManyArgs>(args?: Prisma.SelectSubset<T, ExperienceTagFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ExperienceTag.
   * @param {ExperienceTagCreateArgs} args - Arguments to create a ExperienceTag.
   * @example
   * // Create one ExperienceTag
   * const ExperienceTag = await prisma.experienceTag.create({
   *   data: {
   *     // ... data to create a ExperienceTag
   *   }
   * })
   * 
   */
  create<T extends ExperienceTagCreateArgs>(args: Prisma.SelectSubset<T, ExperienceTagCreateArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ExperienceTags.
   * @param {ExperienceTagCreateManyArgs} args - Arguments to create many ExperienceTags.
   * @example
   * // Create many ExperienceTags
   * const experienceTag = await prisma.experienceTag.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExperienceTagCreateManyArgs>(args?: Prisma.SelectSubset<T, ExperienceTagCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ExperienceTags and returns the data saved in the database.
   * @param {ExperienceTagCreateManyAndReturnArgs} args - Arguments to create many ExperienceTags.
   * @example
   * // Create many ExperienceTags
   * const experienceTag = await prisma.experienceTag.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ExperienceTags and only return the `experienceId`
   * const experienceTagWithExperienceIdOnly = await prisma.experienceTag.createManyAndReturn({
   *   select: { experienceId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExperienceTagCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExperienceTagCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ExperienceTag.
   * @param {ExperienceTagDeleteArgs} args - Arguments to delete one ExperienceTag.
   * @example
   * // Delete one ExperienceTag
   * const ExperienceTag = await prisma.experienceTag.delete({
   *   where: {
   *     // ... filter to delete one ExperienceTag
   *   }
   * })
   * 
   */
  delete<T extends ExperienceTagDeleteArgs>(args: Prisma.SelectSubset<T, ExperienceTagDeleteArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ExperienceTag.
   * @param {ExperienceTagUpdateArgs} args - Arguments to update one ExperienceTag.
   * @example
   * // Update one ExperienceTag
   * const experienceTag = await prisma.experienceTag.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExperienceTagUpdateArgs>(args: Prisma.SelectSubset<T, ExperienceTagUpdateArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ExperienceTags.
   * @param {ExperienceTagDeleteManyArgs} args - Arguments to filter ExperienceTags to delete.
   * @example
   * // Delete a few ExperienceTags
   * const { count } = await prisma.experienceTag.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExperienceTagDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExperienceTagDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExperienceTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperienceTagUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ExperienceTags
   * const experienceTag = await prisma.experienceTag.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExperienceTagUpdateManyArgs>(args: Prisma.SelectSubset<T, ExperienceTagUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ExperienceTags and returns the data updated in the database.
   * @param {ExperienceTagUpdateManyAndReturnArgs} args - Arguments to update many ExperienceTags.
   * @example
   * // Update many ExperienceTags
   * const experienceTag = await prisma.experienceTag.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ExperienceTags and only return the `experienceId`
   * const experienceTagWithExperienceIdOnly = await prisma.experienceTag.updateManyAndReturn({
   *   select: { experienceId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExperienceTagUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExperienceTagUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ExperienceTag.
   * @param {ExperienceTagUpsertArgs} args - Arguments to update or create a ExperienceTag.
   * @example
   * // Update or create a ExperienceTag
   * const experienceTag = await prisma.experienceTag.upsert({
   *   create: {
   *     // ... data to create a ExperienceTag
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ExperienceTag we want to update
   *   }
   * })
   */
  upsert<T extends ExperienceTagUpsertArgs>(args: Prisma.SelectSubset<T, ExperienceTagUpsertArgs<ExtArgs>>): Prisma.Prisma__ExperienceTagClient<runtime.Types.Result.GetResult<Prisma.$ExperienceTagPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ExperienceTags.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperienceTagCountArgs} args - Arguments to filter ExperienceTags to count.
   * @example
   * // Count the number of ExperienceTags
   * const count = await prisma.experienceTag.count({
   *   where: {
   *     // ... the filter for the ExperienceTags we want to count
   *   }
   * })
  **/
  count<T extends ExperienceTagCountArgs>(
    args?: Prisma.Subset<T, ExperienceTagCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExperienceTagCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ExperienceTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperienceTagAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExperienceTagAggregateArgs>(args: Prisma.Subset<T, ExperienceTagAggregateArgs>): Prisma.PrismaPromise<GetExperienceTagAggregateType<T>>

  /**
   * Group by ExperienceTag.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExperienceTagGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExperienceTagGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExperienceTagGroupByArgs['orderBy'] }
      : { orderBy?: ExperienceTagGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExperienceTagGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExperienceTagGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ExperienceTag model
 */
readonly fields: ExperienceTagFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ExperienceTag.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExperienceTagClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  experience<T extends Prisma.ExperienceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ExperienceDefaultArgs<ExtArgs>>): Prisma.Prisma__ExperienceClient<runtime.Types.Result.GetResult<Prisma.$ExperiencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  tag<T extends Prisma.TagDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TagDefaultArgs<ExtArgs>>): Prisma.Prisma__TagClient<runtime.Types.Result.GetResult<Prisma.$TagPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ExperienceTag model
 */
export interface ExperienceTagFieldRefs {
  readonly experienceId: Prisma.FieldRef<"ExperienceTag", 'Int'>
  readonly tagId: Prisma.FieldRef<"ExperienceTag", 'Int'>
}
    

// Custom InputTypes
/**
 * ExperienceTag findUnique
 */
export type ExperienceTagFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * Filter, which ExperienceTag to fetch.
   */
  where: Prisma.ExperienceTagWhereUniqueInput
}

/**
 * ExperienceTag findUniqueOrThrow
 */
export type ExperienceTagFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * Filter, which ExperienceTag to fetch.
   */
  where: Prisma.ExperienceTagWhereUniqueInput
}

/**
 * ExperienceTag findFirst
 */
export type ExperienceTagFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * Filter, which ExperienceTag to fetch.
   */
  where?: Prisma.ExperienceTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperienceTags to fetch.
   */
  orderBy?: Prisma.ExperienceTagOrderByWithRelationInput | Prisma.ExperienceTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExperienceTags.
   */
  cursor?: Prisma.ExperienceTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperienceTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperienceTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExperienceTags.
   */
  distinct?: Prisma.ExperienceTagScalarFieldEnum | Prisma.ExperienceTagScalarFieldEnum[]
}

/**
 * ExperienceTag findFirstOrThrow
 */
export type ExperienceTagFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * Filter, which ExperienceTag to fetch.
   */
  where?: Prisma.ExperienceTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperienceTags to fetch.
   */
  orderBy?: Prisma.ExperienceTagOrderByWithRelationInput | Prisma.ExperienceTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ExperienceTags.
   */
  cursor?: Prisma.ExperienceTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperienceTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperienceTags.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ExperienceTags.
   */
  distinct?: Prisma.ExperienceTagScalarFieldEnum | Prisma.ExperienceTagScalarFieldEnum[]
}

/**
 * ExperienceTag findMany
 */
export type ExperienceTagFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * Filter, which ExperienceTags to fetch.
   */
  where?: Prisma.ExperienceTagWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ExperienceTags to fetch.
   */
  orderBy?: Prisma.ExperienceTagOrderByWithRelationInput | Prisma.ExperienceTagOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ExperienceTags.
   */
  cursor?: Prisma.ExperienceTagWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ExperienceTags from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ExperienceTags.
   */
  skip?: number
  distinct?: Prisma.ExperienceTagScalarFieldEnum | Prisma.ExperienceTagScalarFieldEnum[]
}

/**
 * ExperienceTag create
 */
export type ExperienceTagCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * The data needed to create a ExperienceTag.
   */
  data: Prisma.XOR<Prisma.ExperienceTagCreateInput, Prisma.ExperienceTagUncheckedCreateInput>
}

/**
 * ExperienceTag createMany
 */
export type ExperienceTagCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ExperienceTags.
   */
  data: Prisma.ExperienceTagCreateManyInput | Prisma.ExperienceTagCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ExperienceTag createManyAndReturn
 */
export type ExperienceTagCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * The data used to create many ExperienceTags.
   */
  data: Prisma.ExperienceTagCreateManyInput | Prisma.ExperienceTagCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ExperienceTag update
 */
export type ExperienceTagUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * The data needed to update a ExperienceTag.
   */
  data: Prisma.XOR<Prisma.ExperienceTagUpdateInput, Prisma.ExperienceTagUncheckedUpdateInput>
  /**
   * Choose, which ExperienceTag to update.
   */
  where: Prisma.ExperienceTagWhereUniqueInput
}

/**
 * ExperienceTag updateMany
 */
export type ExperienceTagUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ExperienceTags.
   */
  data: Prisma.XOR<Prisma.ExperienceTagUpdateManyMutationInput, Prisma.ExperienceTagUncheckedUpdateManyInput>
  /**
   * Filter which ExperienceTags to update
   */
  where?: Prisma.ExperienceTagWhereInput
  /**
   * Limit how many ExperienceTags to update.
   */
  limit?: number
}

/**
 * ExperienceTag updateManyAndReturn
 */
export type ExperienceTagUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * The data used to update ExperienceTags.
   */
  data: Prisma.XOR<Prisma.ExperienceTagUpdateManyMutationInput, Prisma.ExperienceTagUncheckedUpdateManyInput>
  /**
   * Filter which ExperienceTags to update
   */
  where?: Prisma.ExperienceTagWhereInput
  /**
   * Limit how many ExperienceTags to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ExperienceTag upsert
 */
export type ExperienceTagUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * The filter to search for the ExperienceTag to update in case it exists.
   */
  where: Prisma.ExperienceTagWhereUniqueInput
  /**
   * In case the ExperienceTag found by the `where` argument doesn't exist, create a new ExperienceTag with this data.
   */
  create: Prisma.XOR<Prisma.ExperienceTagCreateInput, Prisma.ExperienceTagUncheckedCreateInput>
  /**
   * In case the ExperienceTag was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExperienceTagUpdateInput, Prisma.ExperienceTagUncheckedUpdateInput>
}

/**
 * ExperienceTag delete
 */
export type ExperienceTagDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
  /**
   * Filter which ExperienceTag to delete.
   */
  where: Prisma.ExperienceTagWhereUniqueInput
}

/**
 * ExperienceTag deleteMany
 */
export type ExperienceTagDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ExperienceTags to delete
   */
  where?: Prisma.ExperienceTagWhereInput
  /**
   * Limit how many ExperienceTags to delete.
   */
  limit?: number
}

/**
 * ExperienceTag without action
 */
export type ExperienceTagDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExperienceTag
   */
  select?: Prisma.ExperienceTagSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ExperienceTag
   */
  omit?: Prisma.ExperienceTagOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExperienceTagInclude<ExtArgs> | null
}
