
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `TripExperience` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model TripExperience
 * 
 */
export type TripExperienceModel = runtime.Types.Result.DefaultSelection<Prisma.$TripExperiencePayload>

export type AggregateTripExperience = {
  _count: TripExperienceCountAggregateOutputType | null
  _avg: TripExperienceAvgAggregateOutputType | null
  _sum: TripExperienceSumAggregateOutputType | null
  _min: TripExperienceMinAggregateOutputType | null
  _max: TripExperienceMaxAggregateOutputType | null
}

export type TripExperienceAvgAggregateOutputType = {
  tripId: number | null
  experienceId: number | null
  position: number | null
}

export type TripExperienceSumAggregateOutputType = {
  tripId: number | null
  experienceId: number | null
  position: number | null
}

export type TripExperienceMinAggregateOutputType = {
  tripId: number | null
  experienceId: number | null
  position: number | null
}

export type TripExperienceMaxAggregateOutputType = {
  tripId: number | null
  experienceId: number | null
  position: number | null
}

export type TripExperienceCountAggregateOutputType = {
  tripId: number
  experienceId: number
  position: number
  _all: number
}


export type TripExperienceAvgAggregateInputType = {
  tripId?: true
  experienceId?: true
  position?: true
}

export type TripExperienceSumAggregateInputType = {
  tripId?: true
  experienceId?: true
  position?: true
}

export type TripExperienceMinAggregateInputType = {
  tripId?: true
  experienceId?: true
  position?: true
}

export type TripExperienceMaxAggregateInputType = {
  tripId?: true
  experienceId?: true
  position?: true
}

export type TripExperienceCountAggregateInputType = {
  tripId?: true
  experienceId?: true
  position?: true
  _all?: true
}

export type TripExperienceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TripExperience to aggregate.
   */
  where?: Prisma.TripExperienceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TripExperiences to fetch.
   */
  orderBy?: Prisma.TripExperienceOrderByWithRelationInput | Prisma.TripExperienceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TripExperienceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TripExperiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TripExperiences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned TripExperiences
  **/
  _count?: true | TripExperienceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TripExperienceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TripExperienceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TripExperienceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TripExperienceMaxAggregateInputType
}

export type GetTripExperienceAggregateType<T extends TripExperienceAggregateArgs> = {
      [P in keyof T & keyof AggregateTripExperience]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTripExperience[P]>
    : Prisma.GetScalarType<T[P], AggregateTripExperience[P]>
}




export type TripExperienceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TripExperienceWhereInput
  orderBy?: Prisma.TripExperienceOrderByWithAggregationInput | Prisma.TripExperienceOrderByWithAggregationInput[]
  by: Prisma.TripExperienceScalarFieldEnum[] | Prisma.TripExperienceScalarFieldEnum
  having?: Prisma.TripExperienceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TripExperienceCountAggregateInputType | true
  _avg?: TripExperienceAvgAggregateInputType
  _sum?: TripExperienceSumAggregateInputType
  _min?: TripExperienceMinAggregateInputType
  _max?: TripExperienceMaxAggregateInputType
}

export type TripExperienceGroupByOutputType = {
  tripId: number
  experienceId: number
  position: number
  _count: TripExperienceCountAggregateOutputType | null
  _avg: TripExperienceAvgAggregateOutputType | null
  _sum: TripExperienceSumAggregateOutputType | null
  _min: TripExperienceMinAggregateOutputType | null
  _max: TripExperienceMaxAggregateOutputType | null
}

type GetTripExperienceGroupByPayload<T extends TripExperienceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TripExperienceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TripExperienceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TripExperienceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TripExperienceGroupByOutputType[P]>
      }
    >
  >



export type TripExperienceWhereInput = {
  AND?: Prisma.TripExperienceWhereInput | Prisma.TripExperienceWhereInput[]
  OR?: Prisma.TripExperienceWhereInput[]
  NOT?: Prisma.TripExperienceWhereInput | Prisma.TripExperienceWhereInput[]
  tripId?: Prisma.IntFilter<"TripExperience"> | number
  experienceId?: Prisma.IntFilter<"TripExperience"> | number
  position?: Prisma.IntFilter<"TripExperience"> | number
  experience?: Prisma.XOR<Prisma.ExperienceScalarRelationFilter, Prisma.ExperienceWhereInput>
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
}

export type TripExperienceOrderByWithRelationInput = {
  tripId?: Prisma.SortOrder
  experienceId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  experience?: Prisma.ExperienceOrderByWithRelationInput
  trip?: Prisma.TripOrderByWithRelationInput
}

export type TripExperienceWhereUniqueInput = Prisma.AtLeast<{
  tripId_experienceId?: Prisma.TripExperienceTripIdExperienceIdCompoundUniqueInput
  AND?: Prisma.TripExperienceWhereInput | Prisma.TripExperienceWhereInput[]
  OR?: Prisma.TripExperienceWhereInput[]
  NOT?: Prisma.TripExperienceWhereInput | Prisma.TripExperienceWhereInput[]
  tripId?: Prisma.IntFilter<"TripExperience"> | number
  experienceId?: Prisma.IntFilter<"TripExperience"> | number
  position?: Prisma.IntFilter<"TripExperience"> | number
  experience?: Prisma.XOR<Prisma.ExperienceScalarRelationFilter, Prisma.ExperienceWhereInput>
  trip?: Prisma.XOR<Prisma.TripScalarRelationFilter, Prisma.TripWhereInput>
}, "tripId_experienceId">

export type TripExperienceOrderByWithAggregationInput = {
  tripId?: Prisma.SortOrder
  experienceId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  _count?: Prisma.TripExperienceCountOrderByAggregateInput
  _avg?: Prisma.TripExperienceAvgOrderByAggregateInput
  _max?: Prisma.TripExperienceMaxOrderByAggregateInput
  _min?: Prisma.TripExperienceMinOrderByAggregateInput
  _sum?: Prisma.TripExperienceSumOrderByAggregateInput
}

export type TripExperienceScalarWhereWithAggregatesInput = {
  AND?: Prisma.TripExperienceScalarWhereWithAggregatesInput | Prisma.TripExperienceScalarWhereWithAggregatesInput[]
  OR?: Prisma.TripExperienceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TripExperienceScalarWhereWithAggregatesInput | Prisma.TripExperienceScalarWhereWithAggregatesInput[]
  tripId?: Prisma.IntWithAggregatesFilter<"TripExperience"> | number
  experienceId?: Prisma.IntWithAggregatesFilter<"TripExperience"> | number
  position?: Prisma.IntWithAggregatesFilter<"TripExperience"> | number
}

export type TripExperienceCreateInput = {
  position: number
  experience: Prisma.ExperienceCreateNestedOneWithoutTripsInput
  trip: Prisma.TripCreateNestedOneWithoutExperiencesInput
}

export type TripExperienceUncheckedCreateInput = {
  tripId: number
  experienceId: number
  position: number
}

export type TripExperienceUpdateInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.ExperienceUpdateOneRequiredWithoutTripsNestedInput
  trip?: Prisma.TripUpdateOneRequiredWithoutExperiencesNestedInput
}

export type TripExperienceUncheckedUpdateInput = {
  tripId?: Prisma.IntFieldUpdateOperationsInput | number
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TripExperienceCreateManyInput = {
  tripId: number
  experienceId: number
  position: number
}

export type TripExperienceUpdateManyMutationInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TripExperienceUncheckedUpdateManyInput = {
  tripId?: Prisma.IntFieldUpdateOperationsInput | number
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TripExperienceListRelationFilter = {
  every?: Prisma.TripExperienceWhereInput
  some?: Prisma.TripExperienceWhereInput
  none?: Prisma.TripExperienceWhereInput
}

export type TripExperienceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TripExperienceTripIdExperienceIdCompoundUniqueInput = {
  tripId: number
  experienceId: number
}

export type TripExperienceCountOrderByAggregateInput = {
  tripId?: Prisma.SortOrder
  experienceId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type TripExperienceAvgOrderByAggregateInput = {
  tripId?: Prisma.SortOrder
  experienceId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type TripExperienceMaxOrderByAggregateInput = {
  tripId?: Prisma.SortOrder
  experienceId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type TripExperienceMinOrderByAggregateInput = {
  tripId?: Prisma.SortOrder
  experienceId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type TripExperienceSumOrderByAggregateInput = {
  tripId?: Prisma.SortOrder
  experienceId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type TripExperienceCreateNestedManyWithoutExperienceInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutExperienceInput, Prisma.TripExperienceUncheckedCreateWithoutExperienceInput> | Prisma.TripExperienceCreateWithoutExperienceInput[] | Prisma.TripExperienceUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutExperienceInput | Prisma.TripExperienceCreateOrConnectWithoutExperienceInput[]
  createMany?: Prisma.TripExperienceCreateManyExperienceInputEnvelope
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
}

export type TripExperienceUncheckedCreateNestedManyWithoutExperienceInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutExperienceInput, Prisma.TripExperienceUncheckedCreateWithoutExperienceInput> | Prisma.TripExperienceCreateWithoutExperienceInput[] | Prisma.TripExperienceUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutExperienceInput | Prisma.TripExperienceCreateOrConnectWithoutExperienceInput[]
  createMany?: Prisma.TripExperienceCreateManyExperienceInputEnvelope
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
}

export type TripExperienceUpdateManyWithoutExperienceNestedInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutExperienceInput, Prisma.TripExperienceUncheckedCreateWithoutExperienceInput> | Prisma.TripExperienceCreateWithoutExperienceInput[] | Prisma.TripExperienceUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutExperienceInput | Prisma.TripExperienceCreateOrConnectWithoutExperienceInput[]
  upsert?: Prisma.TripExperienceUpsertWithWhereUniqueWithoutExperienceInput | Prisma.TripExperienceUpsertWithWhereUniqueWithoutExperienceInput[]
  createMany?: Prisma.TripExperienceCreateManyExperienceInputEnvelope
  set?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  disconnect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  delete?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  update?: Prisma.TripExperienceUpdateWithWhereUniqueWithoutExperienceInput | Prisma.TripExperienceUpdateWithWhereUniqueWithoutExperienceInput[]
  updateMany?: Prisma.TripExperienceUpdateManyWithWhereWithoutExperienceInput | Prisma.TripExperienceUpdateManyWithWhereWithoutExperienceInput[]
  deleteMany?: Prisma.TripExperienceScalarWhereInput | Prisma.TripExperienceScalarWhereInput[]
}

export type TripExperienceUncheckedUpdateManyWithoutExperienceNestedInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutExperienceInput, Prisma.TripExperienceUncheckedCreateWithoutExperienceInput> | Prisma.TripExperienceCreateWithoutExperienceInput[] | Prisma.TripExperienceUncheckedCreateWithoutExperienceInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutExperienceInput | Prisma.TripExperienceCreateOrConnectWithoutExperienceInput[]
  upsert?: Prisma.TripExperienceUpsertWithWhereUniqueWithoutExperienceInput | Prisma.TripExperienceUpsertWithWhereUniqueWithoutExperienceInput[]
  createMany?: Prisma.TripExperienceCreateManyExperienceInputEnvelope
  set?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  disconnect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  delete?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  update?: Prisma.TripExperienceUpdateWithWhereUniqueWithoutExperienceInput | Prisma.TripExperienceUpdateWithWhereUniqueWithoutExperienceInput[]
  updateMany?: Prisma.TripExperienceUpdateManyWithWhereWithoutExperienceInput | Prisma.TripExperienceUpdateManyWithWhereWithoutExperienceInput[]
  deleteMany?: Prisma.TripExperienceScalarWhereInput | Prisma.TripExperienceScalarWhereInput[]
}

export type TripExperienceCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutTripInput, Prisma.TripExperienceUncheckedCreateWithoutTripInput> | Prisma.TripExperienceCreateWithoutTripInput[] | Prisma.TripExperienceUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutTripInput | Prisma.TripExperienceCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.TripExperienceCreateManyTripInputEnvelope
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
}

export type TripExperienceUncheckedCreateNestedManyWithoutTripInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutTripInput, Prisma.TripExperienceUncheckedCreateWithoutTripInput> | Prisma.TripExperienceCreateWithoutTripInput[] | Prisma.TripExperienceUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutTripInput | Prisma.TripExperienceCreateOrConnectWithoutTripInput[]
  createMany?: Prisma.TripExperienceCreateManyTripInputEnvelope
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
}

export type TripExperienceUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutTripInput, Prisma.TripExperienceUncheckedCreateWithoutTripInput> | Prisma.TripExperienceCreateWithoutTripInput[] | Prisma.TripExperienceUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutTripInput | Prisma.TripExperienceCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.TripExperienceUpsertWithWhereUniqueWithoutTripInput | Prisma.TripExperienceUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.TripExperienceCreateManyTripInputEnvelope
  set?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  disconnect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  delete?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  update?: Prisma.TripExperienceUpdateWithWhereUniqueWithoutTripInput | Prisma.TripExperienceUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.TripExperienceUpdateManyWithWhereWithoutTripInput | Prisma.TripExperienceUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.TripExperienceScalarWhereInput | Prisma.TripExperienceScalarWhereInput[]
}

export type TripExperienceUncheckedUpdateManyWithoutTripNestedInput = {
  create?: Prisma.XOR<Prisma.TripExperienceCreateWithoutTripInput, Prisma.TripExperienceUncheckedCreateWithoutTripInput> | Prisma.TripExperienceCreateWithoutTripInput[] | Prisma.TripExperienceUncheckedCreateWithoutTripInput[]
  connectOrCreate?: Prisma.TripExperienceCreateOrConnectWithoutTripInput | Prisma.TripExperienceCreateOrConnectWithoutTripInput[]
  upsert?: Prisma.TripExperienceUpsertWithWhereUniqueWithoutTripInput | Prisma.TripExperienceUpsertWithWhereUniqueWithoutTripInput[]
  createMany?: Prisma.TripExperienceCreateManyTripInputEnvelope
  set?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  disconnect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  delete?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  connect?: Prisma.TripExperienceWhereUniqueInput | Prisma.TripExperienceWhereUniqueInput[]
  update?: Prisma.TripExperienceUpdateWithWhereUniqueWithoutTripInput | Prisma.TripExperienceUpdateWithWhereUniqueWithoutTripInput[]
  updateMany?: Prisma.TripExperienceUpdateManyWithWhereWithoutTripInput | Prisma.TripExperienceUpdateManyWithWhereWithoutTripInput[]
  deleteMany?: Prisma.TripExperienceScalarWhereInput | Prisma.TripExperienceScalarWhereInput[]
}

export type TripExperienceCreateWithoutExperienceInput = {
  position: number
  trip: Prisma.TripCreateNestedOneWithoutExperiencesInput
}

export type TripExperienceUncheckedCreateWithoutExperienceInput = {
  tripId: number
  position: number
}

export type TripExperienceCreateOrConnectWithoutExperienceInput = {
  where: Prisma.TripExperienceWhereUniqueInput
  create: Prisma.XOR<Prisma.TripExperienceCreateWithoutExperienceInput, Prisma.TripExperienceUncheckedCreateWithoutExperienceInput>
}

export type TripExperienceCreateManyExperienceInputEnvelope = {
  data: Prisma.TripExperienceCreateManyExperienceInput | Prisma.TripExperienceCreateManyExperienceInput[]
  skipDuplicates?: boolean
}

export type TripExperienceUpsertWithWhereUniqueWithoutExperienceInput = {
  where: Prisma.TripExperienceWhereUniqueInput
  update: Prisma.XOR<Prisma.TripExperienceUpdateWithoutExperienceInput, Prisma.TripExperienceUncheckedUpdateWithoutExperienceInput>
  create: Prisma.XOR<Prisma.TripExperienceCreateWithoutExperienceInput, Prisma.TripExperienceUncheckedCreateWithoutExperienceInput>
}

export type TripExperienceUpdateWithWhereUniqueWithoutExperienceInput = {
  where: Prisma.TripExperienceWhereUniqueInput
  data: Prisma.XOR<Prisma.TripExperienceUpdateWithoutExperienceInput, Prisma.TripExperienceUncheckedUpdateWithoutExperienceInput>
}

export type TripExperienceUpdateManyWithWhereWithoutExperienceInput = {
  where: Prisma.TripExperienceScalarWhereInput
  data: Prisma.XOR<Prisma.TripExperienceUpdateManyMutationInput, Prisma.TripExperienceUncheckedUpdateManyWithoutExperienceInput>
}

export type TripExperienceScalarWhereInput = {
  AND?: Prisma.TripExperienceScalarWhereInput | Prisma.TripExperienceScalarWhereInput[]
  OR?: Prisma.TripExperienceScalarWhereInput[]
  NOT?: Prisma.TripExperienceScalarWhereInput | Prisma.TripExperienceScalarWhereInput[]
  tripId?: Prisma.IntFilter<"TripExperience"> | number
  experienceId?: Prisma.IntFilter<"TripExperience"> | number
  position?: Prisma.IntFilter<"TripExperience"> | number
}

export type TripExperienceCreateWithoutTripInput = {
  position: number
  experience: Prisma.ExperienceCreateNestedOneWithoutTripsInput
}

export type TripExperienceUncheckedCreateWithoutTripInput = {
  experienceId: number
  position: number
}

export type TripExperienceCreateOrConnectWithoutTripInput = {
  where: Prisma.TripExperienceWhereUniqueInput
  create: Prisma.XOR<Prisma.TripExperienceCreateWithoutTripInput, Prisma.TripExperienceUncheckedCreateWithoutTripInput>
}

export type TripExperienceCreateManyTripInputEnvelope = {
  data: Prisma.TripExperienceCreateManyTripInput | Prisma.TripExperienceCreateManyTripInput[]
  skipDuplicates?: boolean
}

export type TripExperienceUpsertWithWhereUniqueWithoutTripInput = {
  where: Prisma.TripExperienceWhereUniqueInput
  update: Prisma.XOR<Prisma.TripExperienceUpdateWithoutTripInput, Prisma.TripExperienceUncheckedUpdateWithoutTripInput>
  create: Prisma.XOR<Prisma.TripExperienceCreateWithoutTripInput, Prisma.TripExperienceUncheckedCreateWithoutTripInput>
}

export type TripExperienceUpdateWithWhereUniqueWithoutTripInput = {
  where: Prisma.TripExperienceWhereUniqueInput
  data: Prisma.XOR<Prisma.TripExperienceUpdateWithoutTripInput, Prisma.TripExperienceUncheckedUpdateWithoutTripInput>
}

export type TripExperienceUpdateManyWithWhereWithoutTripInput = {
  where: Prisma.TripExperienceScalarWhereInput
  data: Prisma.XOR<Prisma.TripExperienceUpdateManyMutationInput, Prisma.TripExperienceUncheckedUpdateManyWithoutTripInput>
}

export type TripExperienceCreateManyExperienceInput = {
  tripId: number
  position: number
}

export type TripExperienceUpdateWithoutExperienceInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  trip?: Prisma.TripUpdateOneRequiredWithoutExperiencesNestedInput
}

export type TripExperienceUncheckedUpdateWithoutExperienceInput = {
  tripId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TripExperienceUncheckedUpdateManyWithoutExperienceInput = {
  tripId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TripExperienceCreateManyTripInput = {
  experienceId: number
  position: number
}

export type TripExperienceUpdateWithoutTripInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  experience?: Prisma.ExperienceUpdateOneRequiredWithoutTripsNestedInput
}

export type TripExperienceUncheckedUpdateWithoutTripInput = {
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TripExperienceUncheckedUpdateManyWithoutTripInput = {
  experienceId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}



export type TripExperienceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tripId?: boolean
  experienceId?: boolean
  position?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tripExperience"]>

export type TripExperienceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tripId?: boolean
  experienceId?: boolean
  position?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tripExperience"]>

export type TripExperienceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  tripId?: boolean
  experienceId?: boolean
  position?: boolean
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}, ExtArgs["result"]["tripExperience"]>

export type TripExperienceSelectScalar = {
  tripId?: boolean
  experienceId?: boolean
  position?: boolean
}

export type TripExperienceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"tripId" | "experienceId" | "position", ExtArgs["result"]["tripExperience"]>
export type TripExperienceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}
export type TripExperienceIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}
export type TripExperienceIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  experience?: boolean | Prisma.ExperienceDefaultArgs<ExtArgs>
  trip?: boolean | Prisma.TripDefaultArgs<ExtArgs>
}

export type $TripExperiencePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "TripExperience"
  objects: {
    experience: Prisma.$ExperiencePayload<ExtArgs>
    trip: Prisma.$TripPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    tripId: number
    experienceId: number
    position: number
  }, ExtArgs["result"]["tripExperience"]>
  composites: {}
}

export type TripExperienceGetPayload<S extends boolean | null | undefined | TripExperienceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload, S>

export type TripExperienceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TripExperienceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TripExperienceCountAggregateInputType | true
  }

export interface TripExperienceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['TripExperience'], meta: { name: 'TripExperience' } }
  /**
   * Find zero or one TripExperience that matches the filter.
   * @param {TripExperienceFindUniqueArgs} args - Arguments to find a TripExperience
   * @example
   * // Get one TripExperience
   * const tripExperience = await prisma.tripExperience.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TripExperienceFindUniqueArgs>(args: Prisma.SelectSubset<T, TripExperienceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one TripExperience that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TripExperienceFindUniqueOrThrowArgs} args - Arguments to find a TripExperience
   * @example
   * // Get one TripExperience
   * const tripExperience = await prisma.tripExperience.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TripExperienceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TripExperienceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TripExperience that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripExperienceFindFirstArgs} args - Arguments to find a TripExperience
   * @example
   * // Get one TripExperience
   * const tripExperience = await prisma.tripExperience.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TripExperienceFindFirstArgs>(args?: Prisma.SelectSubset<T, TripExperienceFindFirstArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first TripExperience that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripExperienceFindFirstOrThrowArgs} args - Arguments to find a TripExperience
   * @example
   * // Get one TripExperience
   * const tripExperience = await prisma.tripExperience.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TripExperienceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TripExperienceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more TripExperiences that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripExperienceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all TripExperiences
   * const tripExperiences = await prisma.tripExperience.findMany()
   * 
   * // Get first 10 TripExperiences
   * const tripExperiences = await prisma.tripExperience.findMany({ take: 10 })
   * 
   * // Only select the `tripId`
   * const tripExperienceWithTripIdOnly = await prisma.tripExperience.findMany({ select: { tripId: true } })
   * 
   */
  findMany<T extends TripExperienceFindManyArgs>(args?: Prisma.SelectSubset<T, TripExperienceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a TripExperience.
   * @param {TripExperienceCreateArgs} args - Arguments to create a TripExperience.
   * @example
   * // Create one TripExperience
   * const TripExperience = await prisma.tripExperience.create({
   *   data: {
   *     // ... data to create a TripExperience
   *   }
   * })
   * 
   */
  create<T extends TripExperienceCreateArgs>(args: Prisma.SelectSubset<T, TripExperienceCreateArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many TripExperiences.
   * @param {TripExperienceCreateManyArgs} args - Arguments to create many TripExperiences.
   * @example
   * // Create many TripExperiences
   * const tripExperience = await prisma.tripExperience.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TripExperienceCreateManyArgs>(args?: Prisma.SelectSubset<T, TripExperienceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many TripExperiences and returns the data saved in the database.
   * @param {TripExperienceCreateManyAndReturnArgs} args - Arguments to create many TripExperiences.
   * @example
   * // Create many TripExperiences
   * const tripExperience = await prisma.tripExperience.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many TripExperiences and only return the `tripId`
   * const tripExperienceWithTripIdOnly = await prisma.tripExperience.createManyAndReturn({
   *   select: { tripId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TripExperienceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TripExperienceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a TripExperience.
   * @param {TripExperienceDeleteArgs} args - Arguments to delete one TripExperience.
   * @example
   * // Delete one TripExperience
   * const TripExperience = await prisma.tripExperience.delete({
   *   where: {
   *     // ... filter to delete one TripExperience
   *   }
   * })
   * 
   */
  delete<T extends TripExperienceDeleteArgs>(args: Prisma.SelectSubset<T, TripExperienceDeleteArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one TripExperience.
   * @param {TripExperienceUpdateArgs} args - Arguments to update one TripExperience.
   * @example
   * // Update one TripExperience
   * const tripExperience = await prisma.tripExperience.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TripExperienceUpdateArgs>(args: Prisma.SelectSubset<T, TripExperienceUpdateArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more TripExperiences.
   * @param {TripExperienceDeleteManyArgs} args - Arguments to filter TripExperiences to delete.
   * @example
   * // Delete a few TripExperiences
   * const { count } = await prisma.tripExperience.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TripExperienceDeleteManyArgs>(args?: Prisma.SelectSubset<T, TripExperienceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TripExperiences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripExperienceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many TripExperiences
   * const tripExperience = await prisma.tripExperience.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TripExperienceUpdateManyArgs>(args: Prisma.SelectSubset<T, TripExperienceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more TripExperiences and returns the data updated in the database.
   * @param {TripExperienceUpdateManyAndReturnArgs} args - Arguments to update many TripExperiences.
   * @example
   * // Update many TripExperiences
   * const tripExperience = await prisma.tripExperience.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more TripExperiences and only return the `tripId`
   * const tripExperienceWithTripIdOnly = await prisma.tripExperience.updateManyAndReturn({
   *   select: { tripId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TripExperienceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TripExperienceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one TripExperience.
   * @param {TripExperienceUpsertArgs} args - Arguments to update or create a TripExperience.
   * @example
   * // Update or create a TripExperience
   * const tripExperience = await prisma.tripExperience.upsert({
   *   create: {
   *     // ... data to create a TripExperience
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the TripExperience we want to update
   *   }
   * })
   */
  upsert<T extends TripExperienceUpsertArgs>(args: Prisma.SelectSubset<T, TripExperienceUpsertArgs<ExtArgs>>): Prisma.Prisma__TripExperienceClient<runtime.Types.Result.GetResult<Prisma.$TripExperiencePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of TripExperiences.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripExperienceCountArgs} args - Arguments to filter TripExperiences to count.
   * @example
   * // Count the number of TripExperiences
   * const count = await prisma.tripExperience.count({
   *   where: {
   *     // ... the filter for the TripExperiences we want to count
   *   }
   * })
  **/
  count<T extends TripExperienceCountArgs>(
    args?: Prisma.Subset<T, TripExperienceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TripExperienceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a TripExperience.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripExperienceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TripExperienceAggregateArgs>(args: Prisma.Subset<T, TripExperienceAggregateArgs>): Prisma.PrismaPromise<GetTripExperienceAggregateType<T>>

  /**
   * Group by TripExperience.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TripExperienceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TripExperienceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TripExperienceGroupByArgs['orderBy'] }
      : { orderBy?: TripExperienceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TripExperienceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTripExperienceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the TripExperience model
 */
readonly fields: TripExperienceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for TripExperience.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TripExperienceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  experience<T extends Prisma.ExperienceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ExperienceDefaultArgs<ExtArgs>>): Prisma.Prisma__ExperienceClient<runtime.Types.Result.GetResult<Prisma.$ExperiencePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  trip<T extends Prisma.TripDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.TripDefaultArgs<ExtArgs>>): Prisma.Prisma__TripClient<runtime.Types.Result.GetResult<Prisma.$TripPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the TripExperience model
 */
export interface TripExperienceFieldRefs {
  readonly tripId: Prisma.FieldRef<"TripExperience", 'Int'>
  readonly experienceId: Prisma.FieldRef<"TripExperience", 'Int'>
  readonly position: Prisma.FieldRef<"TripExperience", 'Int'>
}
    

// Custom InputTypes
/**
 * TripExperience findUnique
 */
export type TripExperienceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * Filter, which TripExperience to fetch.
   */
  where: Prisma.TripExperienceWhereUniqueInput
}

/**
 * TripExperience findUniqueOrThrow
 */
export type TripExperienceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * Filter, which TripExperience to fetch.
   */
  where: Prisma.TripExperienceWhereUniqueInput
}

/**
 * TripExperience findFirst
 */
export type TripExperienceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * Filter, which TripExperience to fetch.
   */
  where?: Prisma.TripExperienceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TripExperiences to fetch.
   */
  orderBy?: Prisma.TripExperienceOrderByWithRelationInput | Prisma.TripExperienceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TripExperiences.
   */
  cursor?: Prisma.TripExperienceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TripExperiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TripExperiences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TripExperiences.
   */
  distinct?: Prisma.TripExperienceScalarFieldEnum | Prisma.TripExperienceScalarFieldEnum[]
}

/**
 * TripExperience findFirstOrThrow
 */
export type TripExperienceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * Filter, which TripExperience to fetch.
   */
  where?: Prisma.TripExperienceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TripExperiences to fetch.
   */
  orderBy?: Prisma.TripExperienceOrderByWithRelationInput | Prisma.TripExperienceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for TripExperiences.
   */
  cursor?: Prisma.TripExperienceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TripExperiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TripExperiences.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of TripExperiences.
   */
  distinct?: Prisma.TripExperienceScalarFieldEnum | Prisma.TripExperienceScalarFieldEnum[]
}

/**
 * TripExperience findMany
 */
export type TripExperienceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * Filter, which TripExperiences to fetch.
   */
  where?: Prisma.TripExperienceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of TripExperiences to fetch.
   */
  orderBy?: Prisma.TripExperienceOrderByWithRelationInput | Prisma.TripExperienceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing TripExperiences.
   */
  cursor?: Prisma.TripExperienceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` TripExperiences from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` TripExperiences.
   */
  skip?: number
  distinct?: Prisma.TripExperienceScalarFieldEnum | Prisma.TripExperienceScalarFieldEnum[]
}

/**
 * TripExperience create
 */
export type TripExperienceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * The data needed to create a TripExperience.
   */
  data: Prisma.XOR<Prisma.TripExperienceCreateInput, Prisma.TripExperienceUncheckedCreateInput>
}

/**
 * TripExperience createMany
 */
export type TripExperienceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many TripExperiences.
   */
  data: Prisma.TripExperienceCreateManyInput | Prisma.TripExperienceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * TripExperience createManyAndReturn
 */
export type TripExperienceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * The data used to create many TripExperiences.
   */
  data: Prisma.TripExperienceCreateManyInput | Prisma.TripExperienceCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * TripExperience update
 */
export type TripExperienceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * The data needed to update a TripExperience.
   */
  data: Prisma.XOR<Prisma.TripExperienceUpdateInput, Prisma.TripExperienceUncheckedUpdateInput>
  /**
   * Choose, which TripExperience to update.
   */
  where: Prisma.TripExperienceWhereUniqueInput
}

/**
 * TripExperience updateMany
 */
export type TripExperienceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update TripExperiences.
   */
  data: Prisma.XOR<Prisma.TripExperienceUpdateManyMutationInput, Prisma.TripExperienceUncheckedUpdateManyInput>
  /**
   * Filter which TripExperiences to update
   */
  where?: Prisma.TripExperienceWhereInput
  /**
   * Limit how many TripExperiences to update.
   */
  limit?: number
}

/**
 * TripExperience updateManyAndReturn
 */
export type TripExperienceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * The data used to update TripExperiences.
   */
  data: Prisma.XOR<Prisma.TripExperienceUpdateManyMutationInput, Prisma.TripExperienceUncheckedUpdateManyInput>
  /**
   * Filter which TripExperiences to update
   */
  where?: Prisma.TripExperienceWhereInput
  /**
   * Limit how many TripExperiences to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * TripExperience upsert
 */
export type TripExperienceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * The filter to search for the TripExperience to update in case it exists.
   */
  where: Prisma.TripExperienceWhereUniqueInput
  /**
   * In case the TripExperience found by the `where` argument doesn't exist, create a new TripExperience with this data.
   */
  create: Prisma.XOR<Prisma.TripExperienceCreateInput, Prisma.TripExperienceUncheckedCreateInput>
  /**
   * In case the TripExperience was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TripExperienceUpdateInput, Prisma.TripExperienceUncheckedUpdateInput>
}

/**
 * TripExperience delete
 */
export type TripExperienceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
  /**
   * Filter which TripExperience to delete.
   */
  where: Prisma.TripExperienceWhereUniqueInput
}

/**
 * TripExperience deleteMany
 */
export type TripExperienceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which TripExperiences to delete
   */
  where?: Prisma.TripExperienceWhereInput
  /**
   * Limit how many TripExperiences to delete.
   */
  limit?: number
}

/**
 * TripExperience without action
 */
export type TripExperienceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TripExperience
   */
  select?: Prisma.TripExperienceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TripExperience
   */
  omit?: Prisma.TripExperienceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TripExperienceInclude<ExtArgs> | null
}
