projects:
  - name: Crowd Sourced Travel Planner
    environments:
      - name: Production
        permissions:
          protection: enabled
        services:
          - type: web
            name: server-prod
            runtime: node
            region: oregon
            branch: main
            plan: starter # $7/month (otherwise, the server can have downtime)
            numInstances: 1
            rootDir: server
            envVars:
              - key: NODE_VERSION
                value: 23.10.0
              - key: NODE_ENV
                value: production
              - key: DATABASE_URL
                sync: false # set this to your Neon connection string in Render
              - key: JWT_SECRET
                sync: false

            buildCommand: |
              npm ci
              npx prisma generate --no-engine
              npx prisma migrate deploy

              # build client and place it in public for the server to serve
              # so it can hydrate the session on first render
              cd ../client
              npm ci
              npm run build
              mkdir -p ../server/public
              rm -rf ../server/public/*
              cp -r ./dist/* ../server/public

            startCommand: |
              echo "Starting service..."
              pwd
              npm run start:production
              echo "Service started"
