export const ClientRoutes = {
  HOME: "/",
  MY_EXPERIENCES: "/my-experiences",
  LOGIN: "/login",
  SIGNUP: "/signup",
  EXPLORE: "/explore",
  EXPERIENCE_DETAILS: "/experiences/:id",
  EXPERIENCE_CREATE: "/experiences/create",
  EXPERIENCE_UPDATE: "/experiences/:id/update",
  TRIP_CREATE: "/trips/create",
  TRIP_UPDATE: "/trips/:id/update",
  TRIP_DETAILS: "/trips/:id",
  INTERESTS: "/interests",
  REVIEW_CREATE: "/experiences/:id/reviews/create",
  REVIEW_UPDATE: "/experiences/:id/reviews/:reviewId/update", 
};